/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Data.*;
import Object.*;
import javax.swing.JOptionPane;

/**
 *
 * @author kell
 */
public class DangNhapView extends javax.swing.JFrame {
    KhachData khachdata = new KhachData();
    /**
     * Creates new form DangNhap
     */
    public DangNhapView() {
        initComponents();
        this.setLocation(700, 200);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTaiKhoan = new javax.swing.JTextField();
        jMatKhau = new javax.swing.JPasswordField();
        jRegister = new javax.swing.JButton();
        jLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BOOKSTORE AC");

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 55)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 255));
        jLabel3.setText("Hiệu sách Sofya");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(170, 50, 380, 64);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tài khoản");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 180, 90, 21);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Mật khẩu");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 230, 90, 21);

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khách hàng", "Quản trị viên" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(420, 140, 110, 25);

        jTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTaiKhoanActionPerformed(evt);
            }
        });
        jPanel1.add(jTaiKhoan);
        jTaiKhoan.setBounds(230, 180, 300, 25);

        jMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMatKhauActionPerformed(evt);
            }
        });
        jPanel1.add(jMatKhau);
        jMatKhau.setBounds(230, 230, 300, 25);

        jRegister.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRegister.setText("Đăng kí");
        jRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(jRegister);
        jRegister.setBounds(230, 270, 110, 25);

        jLogin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLogin.setText("Đăng nhập");
        jLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jLogin);
        jLogin.setBounds(420, 270, 110, 25);

        jLabel4.setDisplayedMnemonic('B');
        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/backGround.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 700, 430);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginActionPerformed
        // TODO add your handling code here:
        String taiKhoan = jTaiKhoan.getText();
        String matKhau = new String(jMatKhau.getPassword());
        String phanQuyen = (String)jComboBox1.getSelectedItem();
        if(phanQuyen.equals("Khách hàng")){
            if(taiKhoan.length() < 6 || matKhau.length()<6){
                JOptionPane.showMessageDialog(this, "Tài khoản và mật khẩu phải có độ dài 6-30 kí tự", "Thông báo", HEIGHT);
            }
            else{
                Khach kh = khachdata.dangNhap(taiKhoan, matKhau);
                if(kh==null){
                    JOptionPane.showMessageDialog(this, "Sai thông tin đăng nhập", "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(this, "Đăng nhập thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    KhachHangView jKH = new KhachHangView();
                    jKH.SetInfor(kh);
                    ViTien vi = ViTienData.dangNhap(taiKhoan, matKhau);
                    if(vi == null){
                        JOptionPane.showMessageDialog(this, "Đã sảy ra sự cố");
                    }
                    else{
                        jKH.thongTinVi(vi , kh);
                    }
                    jKH.setVisible(true);
                    dispose();
                }
            }
        }
        else{
            if(taiKhoan.equals("admin") && matKhau.equals("admin")){
//                JOptionPane.showMessageDialog(this, "Bạn đã đăng nhập với tư cách quản trị viên");
                QuanTriView jQT = new QuanTriView();
                jQT.setVisible(true);
                dispose();
            }
            else
                JOptionPane.showMessageDialog(this, "Sai thông tin đăng nhập", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jLoginActionPerformed

    private void jRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegisterActionPerformed
        // TODO add your handling code here:
        String phanQuyen = (String)jComboBox1.getSelectedItem();
        if(phanQuyen.equals("Quản trị viên")){
            JOptionPane.showMessageDialog(this, "Vui lòng liên hệ của hàng để đăng kí làm quản trị viên", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        new DangKyView().setVisible(true);
        
    }//GEN-LAST:event_jRegisterActionPerformed

    private void jTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTaiKhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTaiKhoanActionPerformed

    private void jMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMatKhauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhapView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhapView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhapView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhapView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhapView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jLogin;
    private javax.swing.JPasswordField jMatKhau;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jRegister;
    private javax.swing.JTextField jTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
